

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    action character varying(64) NOT NULL,
    actor_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    details_json oid,
    entity_id bigint NOT NULL,
    entity_type character varying(64) NOT NULL
);


ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.event_seats (
    id bigint NOT NULL,
    seat_number integer NOT NULL,
    row_number integer NOT NULL,
    status character varying(10) NOT NULL,
    version integer NOT NULL,
    event_id bigint NOT NULL,
    CONSTRAINT event_seats_status_check CHECK (((status)::text = ANY ((ARRAY['FREE'::character varying, 'HELD'::character varying, 'LOCKED'::character varying, 'SOLD'::character varying])::text[])))
);


ALTER TABLE public.event_seats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_seats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.events (
    id bigint NOT NULL,
    base_price numeric(12,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_at timestamp(6) without time zone NOT NULL,
    start_at timestamp(6) without time zone NOT NULL,
    status smallint NOT NULL,
    title character varying(255) NOT NULL,
    venue_id bigint NOT NULL,
    CONSTRAINT events_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.order_items (
    id bigint NOT NULL,
    line_total numeric(12,2) NOT NULL,
    seat_no integer NOT NULL,
    row_no integer NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    order_id bigint NOT NULL
);




ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    currency character varying(255) NOT NULL,
    idempotency_key character varying(64),
    status character varying(16) NOT NULL,
    total numeric(38,2) NOT NULL,
    user_id bigint NOT NULL,
    event_id bigint NOT NULL,
    refunded_at timestamp(6) with time zone,
    refund_reason character varying(256),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])))
);



ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    currency character varying(8) NOT NULL,
    idem_key character varying(64),
    provider_ref character varying(64) NOT NULL,
    status character varying(16) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    webhook_hash character varying(64),
    order_id bigint NOT NULL,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['INIT'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying])::text[])))
);



ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.reservation_hold (
    id character varying(36) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    idempotency_key character varying(64) NOT NULL,
    status character varying(16) NOT NULL,
    user_id bigint NOT NULL,
    event_id bigint NOT NULL,
    CONSTRAINT reservation_hold_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'CONSUMED'::character varying])::text[])))
);



CREATE TABLE public.reservation_hold_item (
    id bigint NOT NULL,
    seat_no integer NOT NULL,
    row_no integer NOT NULL,
    hold_id character varying(36) NOT NULL
);



ALTER TABLE public.reservation_hold_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_hold_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);



ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.venues (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255) NOT NULL,
    rows integer NOT NULL,
    seats_per_row integer NOT NULL,
    updated_at timestamp(6) without time zone
);




ALTER TABLE public.venues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.event_seats
    ADD CONSTRAINT event_seats_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.payments
    ADD CONSTRAINT idx_payment_provider_ref UNIQUE (provider_ref);


ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.reservation_hold_item
    ADD CONSTRAINT reservation_hold_item_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.reservation_hold
    ADD CONSTRAINT reservation_hold_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.event_seats
    ADD CONSTRAINT uk_eventseat_event_row_number UNIQUE (event_id, row_number, seat_number);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);




ALTER TABLE ONLY public.venues
    ADD CONSTRAINT uk_venues_name UNIQUE (name);



ALTER TABLE ONLY public.event_seats
    ADD CONSTRAINT uq_eventseat_event_row_number UNIQUE (event_id, row_number, seat_number);



ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uq_o_user_key UNIQUE (user_id, idempotency_key);



ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT uq_oi_order_seat UNIQUE (order_id, row_no, seat_no);



ALTER TABLE ONLY public.reservation_hold
    ADD CONSTRAINT uq_rh_user_event_key UNIQUE (user_id, event_id, idempotency_key);




ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.venues
    ADD CONSTRAINT venues_pkey PRIMARY KEY (id);



CREATE INDEX idx_a_time ON public.audit_log USING btree (created_at);



CREATE INDEX idx_events_name ON public.events USING btree (venue_id);




CREATE INDEX idx_events_start ON public.events USING btree (start_at);




CREATE INDEX idx_events_venue_status ON public.events USING btree (venue_id, status);



CREATE INDEX idx_eventseat_event ON public.event_seats USING btree (event_id);



CREATE INDEX idx_eventseat_event_status ON public.event_seats USING btree (event_id, status);



CREATE INDEX idx_o_created ON public.orders USING btree (created_at);




CREATE INDEX idx_o_event_status ON public.orders USING btree (event_id, status);



CREATE INDEX idx_o_status_created ON public.orders USING btree (status, created_at);


CREATE INDEX idx_o_user ON public.orders USING btree (user_id);



CREATE INDEX idx_o_user_created ON public.orders USING btree (user_id, created_at DESC);




CREATE INDEX idx_o_user_status_created ON public.orders USING btree (user_id, status, created_at DESC);




CREATE INDEX idx_oi_order ON public.order_items USING btree (order_id);




CREATE INDEX idx_payment_order ON public.payments USING btree (order_id);




CREATE INDEX idx_rh_event ON public.reservation_hold USING btree (event_id);




CREATE INDEX idx_rh_expires ON public.reservation_hold USING btree (expires_at);



CREATE INDEX idx_rh_user ON public.reservation_hold USING btree (user_id);



CREATE INDEX idx_rhi_hold ON public.reservation_hold_item USING btree (hold_id);



CREATE INDEX idx_users_email ON public.users USING btree (email);




CREATE INDEX idx_venues_namem ON public.venues USING btree (name);




ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk43g2yroy6l7lfomw37wajkqrn FOREIGN KEY (event_id) REFERENCES public.events(id);




ALTER TABLE ONLY public.reservation_hold_item
    ADD CONSTRAINT fk62ckv5pxlkumw32lco1ee5feu FOREIGN KEY (hold_id) REFERENCES public.reservation_hold(id);



ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES public.orders(id);



ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk_event_venue FOREIGN KEY (venue_id) REFERENCES public.venues(id);



ALTER TABLE ONLY public.event_seats
    ADD CONSTRAINT fk_eventseat_event FOREIGN KEY (event_id) REFERENCES public.events(id);



ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);



ALTER TABLE ONLY public.reservation_hold
    ADD CONSTRAINT fkkwej3pm44el4kx82t3ijnjpoy FOREIGN KEY (event_id) REFERENCES public.events(id);




